name: hlcm_owner

model_type: segmented_discretechoice

segmentation_col: income_quartile

choosers_fit_filters:
- hownrent == 1

choosers_predict_filters:
- hownrent == 1

alts_fit_filters: null

alts_predict_filters:
- unit_tenure == 0

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 15000

prediction_sample_size: null

default_config:
    model_expression: np.log1p(residential_price) + np.log1p(sqft_per_unit) - 1

models:
    1:
        fit_parameters:
            Coefficient:
                np.log1p(residential_price): -0.6156467463505304
                np.log1p(sqft_per_unit): -0.2549903702971792
            Std. Error:
                np.log1p(residential_price): 0.013486133486193042
                np.log1p(sqft_per_unit): 0.011156570629530438
            T-Score:
                np.log1p(residential_price): -45.65035241426484
                np.log1p(sqft_per_unit): -22.85562282214596
        fitted: true
        log_likelihoods:
            convergence: -68067.1371053298
            'null': -68216.3859650534
            ratio: 0.002187874036599591
        name: 1
    2:
        fit_parameters:
            Coefficient:
                np.log1p(residential_price): -0.8075609512738449
                np.log1p(sqft_per_unit): -0.26417077421052243
            Std. Error:
                np.log1p(residential_price): 0.013338100527111426
                np.log1p(sqft_per_unit): 0.01097475926986403
            T-Score:
                np.log1p(residential_price): -60.54542396290777
                np.log1p(sqft_per_unit): -24.07075797424715
        fitted: true
        log_likelihoods:
            convergence: -67960.11476913438
            'null': -68225.59630542537
            ratio: 0.0038912307208354147
        name: 2
    3:
        fit_parameters:
            Coefficient:
                np.log1p(residential_price): -0.5521077014227269
                np.log1p(sqft_per_unit): 0.013691408525234754
            Std. Error:
                np.log1p(residential_price): 0.01347970211960588
                np.log1p(sqft_per_unit): 0.011015287309553166
            T-Score:
                np.log1p(residential_price): -40.95844971378859
                np.log1p(sqft_per_unit): 1.2429461112068028
        fitted: true
        log_likelihoods:
            convergence: -68139.59543941428
            'null': -68363.75141100487
            ratio: 0.0032788717260842093
        name: 3
    4:
        fit_parameters:
            Coefficient:
                np.log1p(residential_price): 1.4815903003272264
                np.log1p(sqft_per_unit): 1.0872841043617676
            Std. Error:
                np.log1p(residential_price): 0.013051682565781111
                np.log1p(sqft_per_unit): 0.01067759462407171
            T-Score:
                np.log1p(residential_price): 113.51718775414125
                np.log1p(sqft_per_unit): 101.82856182895162
        fitted: true
        log_likelihoods:
            convergence: -66915.30494290993
            'null': -68271.6480072852
            ratio: 0.019866856945221723
        name: 4

fitted: true

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
