name: hlcm_owner

model_type: segmented_discretechoice

segmentation_col: income_quartile

choosers_fit_filters:
- hownrent == 1

choosers_predict_filters:
- hownrent == 1

alts_fit_filters: null

alts_predict_filters:
- unit_tenure == 0

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 15000

prediction_sample_size: null

default_config:
    model_expression: np.log1p(residential_price) + np.log1p(sqft_per_unit) + np.log1p(persons
        * ave_hhsize) + np.log1p(white * pct_white) + np.log1p(black * pct_black)
        + np.log1p(hisp * pct_hisp) + np.log1p(asian * pct_asian) + jobs + autoPeakTotal
        + transitPeakTotal + autoOffPeakRetail - 1

models:
    1:
        fit_parameters:
            Coefficient:
                autoOffPeakRetail: 0.33907626166063604
                autoPeakTotal: -0.5059265900161968
                jobs: -0.014210700208545408
                np.log1p(asian * pct_asian): 3.0
                np.log1p(black * pct_black): 3.0
                np.log1p(hisp * pct_hisp): 3.0
                np.log1p(persons * ave_hhsize): 2.4540915067555864
                np.log1p(residential_price): 0.18339300211407808
                np.log1p(sqft_per_unit): 0.010760803694017131
                np.log1p(white * pct_white): 3.0
                transitPeakTotal: 0.013673687322254293
            Std. Error:
                autoOffPeakRetail: 0.05682697220295751
                autoPeakTotal: 0.05416532745606801
                jobs: 0.005861615783189251
                np.log1p(asian * pct_asian): 0.010401563699895453
                np.log1p(black * pct_black): 0.011501060168642514
                np.log1p(hisp * pct_hisp): 0.007250673024445343
                np.log1p(persons * ave_hhsize): 0.021630646132410274
                np.log1p(residential_price): 0.0249365255804643
                np.log1p(sqft_per_unit): 0.014106693930977583
                np.log1p(white * pct_white): 0.008986911886437498
                transitPeakTotal: 0.00486952925354372
            T-Score:
                autoOffPeakRetail: 5.966819074041553
                autoPeakTotal: -9.34041413165165
                jobs: -2.4243656926987285
                np.log1p(asian * pct_asian): 288.418173128157
                np.log1p(black * pct_black): 260.84551824008884
                np.log1p(hisp * pct_hisp): 413.7546942036449
                np.log1p(persons * ave_hhsize): 113.45437818792195
                np.log1p(residential_price): 7.354392716912868
                np.log1p(sqft_per_unit): 0.7628154227112671
                np.log1p(white * pct_white): 333.818784239714
                transitPeakTotal: 2.80801009919049
        fitted: true
        log_likelihoods:
            convergence: -66171.30270912664
            'null': -68161.1239228216
            ratio: 0.02919290497539362
        name: 1
    2:
        fit_parameters:
            Coefficient:
                autoOffPeakRetail: 0.5736864662288649
                autoPeakTotal: -0.7204151937528653
                jobs: -0.011703170866079981
                np.log1p(asian * pct_asian): 3.0
                np.log1p(black * pct_black): 3.0
                np.log1p(hisp * pct_hisp): 3.0
                np.log1p(persons * ave_hhsize): 2.531801610077895
                np.log1p(residential_price): 0.2237247917715945
                np.log1p(sqft_per_unit): 0.021298674858513292
                np.log1p(white * pct_white): 3.0
                transitPeakTotal: -0.003865420434458979
            Std. Error:
                autoOffPeakRetail: 0.05452597975074607
                autoPeakTotal: 0.05220392927004924
                jobs: 0.005805291528050298
                np.log1p(asian * pct_asian): 0.010236608856968487
                np.log1p(black * pct_black): 0.011673718721522086
                np.log1p(hisp * pct_hisp): 0.006994794112006544
                np.log1p(persons * ave_hhsize): 0.020035186503520076
                np.log1p(residential_price): 0.025336133020252755
                np.log1p(sqft_per_unit): 0.014212585646567088
                np.log1p(white * pct_white): 0.008856040368076166
                transitPeakTotal: 0.004744180644216534
            T-Score:
                autoOffPeakRetail: 10.52134173198447
                autoPeakTotal: -13.800018577647302
                jobs: -2.0159488648471857
                np.log1p(asian * pct_asian): 293.0658035212291
                np.log1p(black * pct_black): 256.9875179936529
                np.log1p(hisp * pct_hisp): 428.8903936215233
                np.log1p(persons * ave_hhsize): 126.36775852488675
                np.log1p(residential_price): 8.830265912827237
                np.log1p(sqft_per_unit): 1.498578470389572
                np.log1p(white * pct_white): 338.75184341009304
                transitPeakTotal: -0.8147709213331028
        fitted: true
        log_likelihoods:
            convergence: -66022.9633854273
            'null': -68174.93943337955
            ratio: 0.0315654999599253
        name: 2
    3:
        fit_parameters:
            Coefficient:
                autoOffPeakRetail: 0.6027059322037337
                autoPeakTotal: -0.6974863354615239
                jobs: -0.03043160921046149
                np.log1p(asian * pct_asian): 3.0
                np.log1p(black * pct_black): 3.0
                np.log1p(hisp * pct_hisp): 3.0
                np.log1p(persons * ave_hhsize): 3.0
                np.log1p(residential_price): 0.5698053841954817
                np.log1p(sqft_per_unit): 0.25472573042770075
                np.log1p(white * pct_white): 3.0
                transitPeakTotal: -0.030329645954617186
            Std. Error:
                autoOffPeakRetail: 0.05411968453042445
                autoPeakTotal: 0.05170670577917641
                jobs: 0.0056276508722069565
                np.log1p(asian * pct_asian): 0.009688134563063309
                np.log1p(black * pct_black): 0.011685280379308377
                np.log1p(hisp * pct_hisp): 0.00719256288582374
                np.log1p(persons * ave_hhsize): 0.020350386540807848
                np.log1p(residential_price): 0.026230494126699717
                np.log1p(sqft_per_unit): 0.014498956787061574
                np.log1p(white * pct_white): 0.008546142373792512
                transitPeakTotal: 0.004666768169268254
            T-Score:
                autoOffPeakRetail: 11.136538164129739
                autoPeakTotal: -13.489281998359663
                jobs: -5.407515480527195
                np.log1p(asian * pct_asian): 309.65713579554415
                np.log1p(black * pct_black): 256.73324923484313
                np.log1p(hisp * pct_hisp): 417.09750024054466
                np.log1p(persons * ave_hhsize): 147.41734728154748
                np.log1p(residential_price): 21.723013735203843
                np.log1p(sqft_per_unit): 17.568555736024415
                np.log1p(white * pct_white): 351.03557474068776
                transitPeakTotal: -6.499068489055212
        fitted: true
        log_likelihoods:
            convergence: -66045.32152004531
            'null': -68414.40828305068
            ratio: 0.03462847698987259
        name: 3
    4:
        fit_parameters:
            Coefficient:
                autoOffPeakRetail: 0.872391013840294
                autoPeakTotal: -0.9265532530227754
                jobs: -0.022474309452739892
                np.log1p(asian * pct_asian): 3.0
                np.log1p(black * pct_black): 3.0
                np.log1p(hisp * pct_hisp): 3.0
                np.log1p(persons * ave_hhsize): 3.0
                np.log1p(residential_price): 2.491417402986866
                np.log1p(sqft_per_unit): 1.2376514324333414
                np.log1p(white * pct_white): 3.0
                transitPeakTotal: -0.07386911148086539
            Std. Error:
                autoOffPeakRetail: 0.05939746230882829
                autoPeakTotal: 0.055101184850207444
                jobs: 0.005204194368545654
                np.log1p(asian * pct_asian): 0.011558299989301943
                np.log1p(black * pct_black): 0.014460829585571785
                np.log1p(hisp * pct_hisp): 0.009026656023390481
                np.log1p(persons * ave_hhsize): 0.02178314324325523
                np.log1p(residential_price): 0.026354034860810827
                np.log1p(sqft_per_unit): 0.01469062069804245
                np.log1p(white * pct_white): 0.010630675888832784
                transitPeakTotal: 0.004435040330259127
            T-Score:
                autoOffPeakRetail: 14.687344878547613
                autoPeakTotal: -16.81548691814178
                jobs: -4.318499245257914
                np.log1p(asian * pct_asian): 259.55374084222774
                np.log1p(black * pct_black): 207.45697764070422
                np.log1p(hisp * pct_hisp): 332.348988620614
                np.log1p(persons * ave_hhsize): 137.72117120557877
                np.log1p(residential_price): 94.536469126846
                np.log1p(sqft_per_unit): 84.24772906962744
                np.log1p(white * pct_white): 282.2021884000257
                transitPeakTotal: -16.655792502466248
        fitted: true
        log_likelihoods:
            convergence: -64471.61129234616
            'null': -68225.59630542537
            ratio: 0.05502311766208312
        name: 4

fitted: true

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
